name: smart_trip_planner
description: A smart trip planner app with clean architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  http: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  dio: ^5.3.2
  url_launcher: ^6.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  mockito: ^5.4.2
  http_mock_adapter: ^0.6.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

